"""Engine for ``vena-fm-post-train``.

Renders the standard plot bundle for a finished FM training run. The engine
is a thin wrapper around :class:`vena.model.fm.post_train.PostTrainRunner` —
it validates the run directory layout, then delegates rendering.

Used in two modes:

* **Standalone** — ``vena-fm-post-train cfg.yaml`` re-renders plots for an
  existing run directory.
* **Auto-fire** — :class:`routines.fm.train.engine.FMTrainRoutineEngine`
  calls :func:`render_for_run_dir` after ``trainer.fit()`` finishes.
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, field_validator

logger = logging.getLogger(__name__)

__all__ = ["PostTrainEngine", "PostTrainRoutineConfig", "render_for_run_dir"]


class PostTrainRoutineConfig(BaseModel):
    """Pydantic config for ``vena-fm-post-train``.

    One required field, ``run_dir`` (absolute or relative path to a finished
    FM training run directory). ``formats`` defaults to PNG only because the
    primary consumer of these plots is intermediate Picasso inspection;
    paper-quality PDF/SVG will be regenerated by ``routines/release/paper``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    run_dir: Path
    formats: tuple[str, ...] = ("png",)

    @field_validator("formats", mode="before")
    @classmethod
    def _normalise_formats(cls, value: object) -> tuple[str, ...]:
        if isinstance(value, str):
            return (value,)
        if isinstance(value, (list, tuple)):
            return tuple(str(v) for v in value)
        raise TypeError(f"formats must be a str or sequence of str, got {type(value).__name__}")

    @classmethod
    def from_yaml(cls, path: Path | str) -> PostTrainRoutineConfig:
        path = Path(path)
        with path.open("r") as f:
            raw = yaml.safe_load(f) or {}
        return cls.model_validate(raw)


class PostTrainEngine:
    """Orchestrate rendering of the post-training plot bundle.

    Parameters
    ----------
    cfg : PostTrainRoutineConfig
        Validated config.
    """

    def __init__(self, cfg: PostTrainRoutineConfig) -> None:
        self.cfg = cfg

    def run(self) -> Path:
        """Render plots and return the resulting ``<run_dir>/plots/`` path."""
        run_dir = self.cfg.run_dir
        if not run_dir.exists():
            raise FileNotFoundError(f"run_dir does not exist: {run_dir}")
        metrics_csv = run_dir / "metrics" / "train_epoch.csv"
        if not metrics_csv.exists():
            raise FileNotFoundError(f"train_epoch.csv missing at {metrics_csv}; nothing to plot")

        plots_dir = render_for_run_dir(run_dir, formats=self.cfg.formats)
        logger.info("post-train artifacts: %s", plots_dir)
        return plots_dir


def render_for_run_dir(run_dir: Path, *, formats: tuple[str, ...] = ("png",)) -> Path:
    """Render the plot bundle for ``run_dir``; return the plots directory.

    Importable from the train engine so the auto-fire hook does not need to
    construct a ``PostTrainRoutineConfig``.
    """
    from vena.model.fm.post_train import PostTrainRunner

    runner = PostTrainRunner(run_dir, formats=formats)
    runner.run()
    return runner.plots_dir
